version: '3.7'

services:
  mysql:
    image: mysql:8.0

  react-frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://127.0.0.1:5000"
    volumes:
      - ./frontend:/app  # Mount the local source code to the container
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"  # React development server runs on port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true  # Optional: Ensures file watching works in Docker