version: '3.7'

services:
  nginx:
    ports: []
    volumes: []
    depends_on: []
    command: ["/bin/true"]  # Prevents Nginx from doing anything
    networks:
      - app-network
  flask_app:
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_APP: app.py
    volumes:
      - ./flask-finance-server:/app  # Map source code for hot-reloading
      - ./migrations:/app/migrations
    command: flask run  # Enable development server df
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    networks:
      - app-network

  react_frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://127.0.0.1:5000"
    volumes:
      - ./frontend:/app  # Mount the local source code to the container
      - /app/node_modules  # Prevent overwriting node_modules
    ports:
      - "3000:3000"  # React development server runs on port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true  # Optional: Ensures file watching works in Docker
    networks:
      - app-network