version: '3.7'

services:
  flask_app:
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - ./migrations:/app/migrations  # Persist migrations
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app  # Use Gunicorn for production
    networks:
      - app-network
  mysql:
    image: mysql:5.7
    networks:
      - app-network
  react_frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "https://homelab.servequake.com/api/"
    volumes:
      - ./frontend:/app  # Mount the local source code to the container
      - react_build:/app/build  # Store build artifacts in a shared Docker volume
    ports:
      - "3000:3000"  # React development server runs on port 3000    
    command: npm run build
    networks:
      - app-network
  