version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Serve HTTP on local network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html  # Serve built React app
    depends_on:
      - flask_app
      - react_frontend
    networks:
      - app-network
  flask_app:
    build:
      context: ./flask-finance-server
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: bookkeeper_db
      MYSQL_USER: bookkeeper_user
      MYSQL_PASSWORD: bookkeeper_user_sql_password_for_a_long_time
      MYSQL_HOST: mysql
    restart: always
    volumes:
      - ./migrations:/app/migrations  # Persist migrations
      - ./flask-finance-server:/app  # Map the app source code (optional)
    command: flask run  # Starts the app using Flask CLI
    depends_on:
      - mysql
    networks:
      - app-network

  react_frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: "http://192.168.86.33/api/"
    volumes:
      - ./frontend:/app  # Mount the local source code to the container
      - react_build:/app/build  # Store build artifacts in a shared Docker volume
    ports:
      - "3000:3000"  # React development server runs on port 3000    
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootimus_maximus
      MYSQL_DATABASE: bookkeeper_db
      MYSQL_USER: bookkeeper_user
      MYSQL_PASSWORD: bookkeeper_user_sql_password_for_a_long_time
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:
  react_build:  # Define shared volum

networks:
  app-network:
    driver: bridge